import subprocess
from pathlib import Path

from spjaffolding.templates import generate_pyproject_toml, generate_cli_py, generate_init_py

def execute_subprocess(cmd: list[str], cwd: Path) -> None:
    try:
        subprocess.run(cmd, cwd=cwd, check=True, text=True, capture_output=True)
    except subprocess.CalledProcessError as e:
        print(f"Subprocess failed: {cmd}\nStdout: {e.stdout}\nStderr: {e.stderr}")
        raise

def orchestrate_generation(tool_name: str, description: str, project_domain: str, output_dir: Path = Path.cwd()) -> None:
    """Executes the complete generation process via un-mocked subprocess workflows."""
    project_path = output_dir / tool_name

    # Step 1: Execute `uv init`
    # We call uv init on a specific dir
    if not project_path.exists():
        project_path.mkdir(parents=True)
    execute_subprocess(["uv", "init", "--bare", "--name", tool_name], cwd=project_path)

    # Step 2: Overwrite pyproject.toml generated by uv with our rigorous dependency clusters
    toml_path = project_path / "pyproject.toml"
    with open(toml_path, "w", encoding="utf-8") as f:
        f.write(generate_pyproject_toml(tool_name, description))

    # Step 3: Taxonomy generation / Hierarchy structural layout
    src_dir = project_path / "src" / tool_name
    src_dir.mkdir(parents=True, exist_ok=True)
    
    # Initialize workspace structure
    workspace_dir = project_path / "workspaces"
    workspace_dir.mkdir(parents=True, exist_ok=True)

    # Recreate the init py
    init_path = src_dir / "__init__.py"
    with open(init_path, "w", encoding="utf-8") as f:
        f.write(generate_init_py())

    # Create the cli.py file with the Finite State Machine skeleton
    cli_path = src_dir / "cli.py"
    with open(cli_path, "w", encoding="utf-8") as f:
        f.write(generate_cli_py(tool_name))

    # Condition on `project_domain`
    if project_domain == "numerical_ml":
        (src_dir / "data_prep").mkdir(parents=True, exist_ok=True)
        (src_dir / "models").mkdir(parents=True, exist_ok=True)
        (src_dir / "training").mkdir(parents=True, exist_ok=True)
    elif project_domain == "llm_scraping":
        (src_dir / "scraping").mkdir(parents=True, exist_ok=True)
        (src_dir / "vector_db").mkdir(parents=True, exist_ok=True)
        (src_dir / "llm_orchestration").mkdir(parents=True, exist_ok=True)
    else:
        raise ValueError(f"Unknown project_domain: {project_domain}")
        
    # Create a dummy README.md for hatchling build system
    readme_path = project_path / "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(f"# {tool_name}\n\n{description}\n")

    # Step 4: Execute `uv sync` to lock the updated setup
    execute_subprocess(["uv", "sync"], cwd=project_path)
